### ISSUE TITLE
Wrong topology

### ISSUE THREAD

**Issue by DieMyst** [fluencelabs/aqua#215] opened 2021-07-23 13:57 UTC
In this code
```
service OpH("op"):
  get_str() -> string
  pr() -> []string
  op(s: string)
  get_arr() -> []string

func registerKeyPutValue(node_id: string) -> []string:
  on node_id:
    nodes <- OpH.pr()
  on node_id:
      for n <- nodes par:
        on n:
          OpH.op("in")
  <- nodes
  ```
  No hop to `relay` before respone call
  ```
  (seq
 (seq
  (seq
   (seq
    (seq
     (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
     (call %init_peer_id% ("getDataSrv" "node_id") [] node_id)
    )
    (call -relay- ("op" "noop") [])
   )
   (call node_id ("op" "pr") [] nodes)
  )
  (fold nodes n
   (par
    (call n ("op" "op") ["in"])
    (next n)
   )
  )
 )
 (call %init_peer_id% ("callbackSrv" "response") [nodes])
 ```

**Comment by alari** [comment] 2021-08-02 11:00
Affects #205

**Comment by folex** [comment] 2021-09-13 12:30
Also, in this example
```
func initTopicAndSubscribeBlocking(
  topic: string, value: string, 
  relay_id: ?PeerId, service_id: ?string, 
  -- progress: string -> ()
) -> DhtResult:
  results: *DhtResult
  on HOST_PEER_ID:
    nodes <- getNeighbours(topic)
    for n <- nodes par:
      on n:
        try:
          t <- Peer.timestamp_sec()
          AquaDHT.register_key(topic, t, false, 0)
          result <- AquaDHT.put_value(topic, value, t, relay_id, service_id, 0)
          if result.success:
            results <<- result
            -- co progress(n)
  <- results!0
```

After every fold iteration, there's a hop to `init_peer_id` that is missing a hop to relay. 

However, if you uncomment the commented lines, it will work fine.

**Comment by alari** [comment] 2021-10-05 07:01
Duplicate of #205

**Comment by alari** [comment] 2021-11-10 13:25
This should not be an issue anymore, as `fold par` is wrapped with `par null`, so that there's no need to hop back to `%init_peer_id%`.

**Closed** 2021-11-10 13:32 UTC
Labels: bug
