### ISSUE TITLE
Add syntax sugar to convert a value into collection

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua#191] opened 2021-07-05 18:20 UTC
```
response <- Op.identity("chat")
                                   ^^^^^^=
                                   Types mismatch, expected: ?string, given: literal(string)
```

**Comment by folex** [comment] 2021-07-05 19:18
Currently there's no special syntax to convert string literal to `?string`. You can do the following:
```scala
service MyOp("op"):
  identity(string) -> string

response <- MyOp.identity("chat")
```

**Comment by alari** [comment] 2021-09-07 07:32
Duplicate of #273

**Closed by alari** 2021-09-07 07:32 UTC
Labels: sugar
